_left    = keyboard_check(vk_left)
_right   = keyboard_check(vk_right)
_up      = keyboard_check(vk_up)
_down    = keyboard_check(vk_down)
_space   = keyboard_check(vk_space)
_esc     = keyboard_check(vk_escape)

_left_p  = keyboard_check_pressed(vk_left)
_right_p = keyboard_check_pressed(vk_right)
_up_p    = keyboard_check_pressed(vk_up)
_down_p  = keyboard_check_pressed(vk_down)
_space_p = keyboard_check_pressed(vk_space)
_esc_p   = keyboard_check_pressed(vk_escape)

_q       = keyboard_check(ord("Q"))
_q_p     = keyboard_check_pressed(ord("Q"))